name: Linux

on:
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os.runs-on }}
    container:
      image: ghcr.io/pkgforge-dev/archlinux:latest
      options: --privileged --device /dev/fuse

    strategy:
      fail-fast: false
      matrix:
        os:
          - runs-on: ubuntu-24.04
            arch: amd64
          - runs-on: ubuntu-24.04-arm
            arch: aarch64

    steps:
      - name: Install Git
        run: pacman -Syu --noconfirm git

      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Initial setup
        uses: ./.github/workflows/setup
        with:
          arch: ${{ matrix.os.arch }}

      - name: Install dependencies
        run: ./.github/workflows/scripts/linux/deps.sh

      - name: Build
        uses: ./.github/workflows/build
